services:
  - type: web
    name: smart-parking-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JDBC_DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
